name: Deploy Prod configuration to Digital Ocean Staging

on:
  workflow_run:
    workflows: ["Create and publish a Docker image"]
    types: [completed]
    branches:
    - 'main'
    - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Digital Ocean droplet via SSH action
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.ACCESS_KEY }}
        script: |
            temp_env_file=$(mktemp)
            
            echo ${{secrets.COMPOSE_ENV}} >> $temp_env_file
            echo "ENV_PATH=$temp_env_file" >> $temp_env_file
            if [ ! -d socialpredict-deploy ]
            then
                git clone ${{ github.server_url }}/${{ github.repository }} socialpredict-deploy
            else
                cd socialpredict-deploy
                git fetch origin
            fi
            git checkout ${{ github.sha }}

            docker compose -f ./scripts/docker-compose-prod.yaml \
             --env-file $temp_env_file \
             up -d --no-deps backend